---
- ansible.builtin.include_task: pve_community.yaml
  when:
    - not proxmox_ve_enterprise is undefined or not proxmox_ve_enterprise

- name: Install the Dark Theme
  ansible.builtin.include_role:
    name: notmycloud.pve_discord_dark
