---
- name: 'Disable Enterprise PVE repo'
  ansible.builtin.apt_repository:
    repo: 'deb https://enterprise.proxmox.com/debian/pve {{ item }} pve-enterprise'
    state: 'absent'
  with_list:
    - stretch
    - buster
    - bullseye
    - "{{ ansible_distribution_release }}"
  when:
    - proxmox_ve_enterprise is undefined or proxmox_ve_enterprise == false

- name: 'Enable Community PVE current repo'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription'
    state: 'present'
  when:
    - proxmox_ve_enterprise is undefined or proxmox_ve_enterprise == false

- name: Get Proxmox version for backup file
  ansible.builtin.set_fact:
    proxmox_version: "{{ ansible_facts.packages['proxmox-ve'][0].version }}"
  when:
    - proxmox_ve_enterprise is undefined or proxmox_ve_enterprise == false

- name: Check if subscription fix is already applied
  ansible.builtin.command: grep -Fq 'if (res === null || res === undefined || !res || false) {' {{ proxmoxlib }}
  register: check_fixed
  failed_when: check_fixed.rc > 1
  check_mode: false
  ignore_errors: true
  changed_when: false
  when:
    - proxmox_ve_enterprise is undefined or proxmox_ve_enterprise == false

- name: Backup up original file
  ansible.builtin.copy:
    remote_src: true
    src: "{{ proxmox_ve_lib_file }}"
    dest: "{{ proxmox_ve_lib_file }}.bak-{{ proxmox_version }}"
    force: false
    mode: '0644'
  when:
    - check_fixed.rc == 1
    - proxmox_ve_enterprise is undefined or proxmox_ve_enterprise == false

- name: Modify line which performs license check
  ansible.builtin.replace:
    path: "{{ proxmox_ve_lib_file }}"
    regexp: res\s*\.data\.status\.toLowerCase\(\) !== 'active'
    replace: "false"
  notify:
    - Restart pveproxy
  when:
    - check_fixed.rc == 1
    - proxmox_ve_enterprise is undefined or proxmox_ve_enterprise == false

- name: Install the Dark Theme
  ansible.builtin.include_role:
    name: notmycloud.pve_discord_dark