---
- name: 'Disable Enterprise PVE repo'
  ansible.builtin.apt_repository:
    repo: 'deb https://enterprise.proxmox.com/debian/pve {{ item }} pve-enterprise'
    state: 'absent'
  with_list:
    - stretch
    - buster
    - bullseye
    - "{{ ansible_distribution_release }}"

- name: 'Enable Community PVE current repo'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription'
    state: 'present'

- ansible.builtin.include_task: pve_subscription_notice.yaml
